### ISSUE TITLE
Screen top-bar right-click context menu does not appear for electronjs based apps like VSCode, Signal Messenger

### ISSUE THREAD

**Issue by pavangayakwad** [elementary/switchboard-plug-applications#53] opened 2019-12-04 10:22 UTC
## Describe the bug
All native elementary apps have the context menu when a user right-click on the screen top-bar. This option is greatly useful when we want to minimise the window and do other operations as required.

UPDATE:
I just now noticed it is same with "GNU Image Manipulation Program" too! So basically I cannot minimise the application. This is filling-up my screen and its painful.

![image](https://user-images.githubusercontent.com/1834890/70132936-32757a80-16ab-11ea-8176-4988c0b6cbfe.png)

However, this behaviour is not common across all sorts of applications. 
For example, If I install any application like Visual Studio Code, Signal messenger ..etc that are built using Electronjs framework, open the application and when right click on their application top-bar, the elementary context menu does not appear (as show in the above pic).

This needs to be fixed as this not only surprises user also it takes away the best window experience we enjoy in elementary.

### To Reproduce
1. Install visual studio code from here: https://code.visualstudio.com/
2. Open the VS Code application
3. Right click on the top-bar and elementary context menu does not show up.

### Expected behavior
Right click on the top-bar of the applications developed using electronjs should continue to show the elementary context menu to manage the window.

## Platform Information
![image](https://user-images.githubusercontent.com/1834890/70134097-605bbe80-16ad-11ea-8231-69d57dcbf209.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by ryonakano** [comment] 2019-12-04 10:31
Thanks for your report, but it seems to be duplicate of elementary/gala#174

**Closed by ryonakano** 2019-12-04 10:31 UTC
