### ISSUE TITLE
Apps Do Not Properly Request Some Permissions

### ISSUE THREAD

**Issue by theuser18** [elementary/switchboard-plug-applications#165] opened 2021-08-19 17:51 UTC
## What Happened
Some apps cannot properly request the proper permission, and thus fail to work in certain ways. There needs to be a way for apps to "request" certain permissions if they are not allowed to have them automatically.

## Expected Behavior
The apps should have access to what they need to function and have the relevant permissions enabled without troubleshooting.
Firefox should allow me to open a profile folder directory without a problem. Similarly, screen recorder apps were unable to write the recording to their home subfolder location since the permission was disabled, unknown to me.

## Steps to Reproduce
Take Firefox from FlatHub for example. I was migrating a profile from my old OS to eOS 6. This was also a problem with multiple screen recorder apps I tried.

1. When I went to FF's about:profiles to open the default profile folder in the file manager, nothing happened when I clicked "Open Directory." Similarly, I was unable to manually navigate to the profile in the Files app since it was not created.
2. The solution was to manually enable the Home folder permission in settings. This took quite awhile for me to figure out.

## Platform Information
Elementary OS 6
Firefox 91

**Comment by jhaygood86** [comment] 2021-09-16 12:28
Apps can request permissions for specific things by using portals, but the app will need to do the work to support it. I don't think elementary OS can anything automatically, especially with a non-curated app like Firefox.

**Comment by BMiZEL** [comment] 2023-10-24 05:25
On Elementary OS 6 as well as 7 & 7.1 the problem is that even if you change the settings, after each reboot,they are resest to default. So this option is basically window-dressing and you cannot rely on it. It would be great if this can be fixed.

**Comment by danirabbit** [comment] 2024-03-29 16:26
Sounds like this is a duplicate of #171

**Closed by danirabbit** 2024-03-29 16:26 UTC
